In [2]:
from scipy.io import loadmat, savemat

import numpy as np

In [142]:
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.metrics import accuracy_score, matthews_corrcoef
from sklearn.metrics import f1_score, precision_score

for c in range(5):
    for f in range(10):
        filename = 'encoding_3106_lrg/new_encoding_3106_lrg_' +str(c) + '_' +  str(f) + '.mat'
        result = loadmat(filename)
        test_y = result['test_y']
        pred_y = result['pred_y']

        tmp = np.zeros(pred_y.shape)


        resauc = []
        for i in range(14):
            fpr, tpr, _ = roc_curve(test_y[:, i], pred_y[:, i])
            roc_auc = auc(fpr, tpr)
            resauc.append(roc_auc)


        resmcc = []
        resf1 = []
        for t in np.arange(0,1,0.01):
            tmp[pred_y < t] = 0
            tmp[pred_y >= t] = 1
            for i in range(14):
                resmcc.append(matthews_corrcoef(test_y[:,i], tmp[:, i]))
                resf1.append(f1_score(test_y[:,i], tmp[:, i]))
        resmcc = np.array(resmcc).reshape((100, 14))
        resf1 = np.array(resf1).reshape((100, 14))

        print('{}, auc: {:.4f}, {:.4f}, mcc: {:.4f}, f1: {:.4f}'.format(f, 
            np.amax(resauc), np.average(resauc), np.amax(resmcc), np.amax(resf1)))
    #     print('{}, auc: {:.4f}, {:.4f}'.format(f,
    #             np.amax(resauc), np.average(resauc)))

0, auc: 0.8165, 0.7344, mcc: 0.3946, f1: 0.6238
1, auc: 0.8797, 0.8202, mcc: 0.5103, f1: 0.7024
2, auc: 0.8938, 0.8608, mcc: 0.5723, f1: 0.7349
3, auc: 0.9055, 0.8837, mcc: 0.6065, f1: 0.7545
4, auc: 0.9078, 0.8900, mcc: 0.6159, f1: 0.7614
5, auc: 0.9219, 0.8930, mcc: 0.6205, f1: 0.7619
6, auc: 0.9220, 0.8973, mcc: 0.6299, f1: 0.7669
7, auc: 0.9376, 0.9042, mcc: 0.6381, f1: 0.7778
8, auc: 0.9246, 0.9053, mcc: 0.6326, f1: 0.7667
9, auc: 0.9255, 0.9064, mcc: 0.6419, f1: 0.7775
0, auc: 0.8031, 0.7263, mcc: 0.3699, f1: 0.6305
1, auc: 0.8719, 0.8031, mcc: 0.5077, f1: 0.6933
2, auc: 0.8863, 0.8476, mcc: 0.5765, f1: 0.7416
3, auc: 0.9100, 0.8707, mcc: 0.5946, f1: 0.7491
4, auc: 0.9267, 0.8803, mcc: 0.6010, f1: 0.7500
5, auc: 0.9156, 0.8848, mcc: 0.6133, f1: 0.7639
6, auc: 0.9258, 0.8912, mcc: 0.6098, f1: 0.7619
7, auc: 0.9334, 0.8969, mcc: 0.6204, f1: 0.7700
8, auc: 0.9324, 0.8992, mcc: 0.6312, f1: 0.7704
9, auc: 0.9381, 0.8986, mcc: 0.6354, f1: 0.7755
0, auc: 0.8116, 0.7259, mcc: 0.3555, f1:

In [135]:
for f in range(10):
    filename = 'new_result_pssm/new_pssm_4802_' + str(f) + '.mat'
    result = loadmat(filename)
    test_y = result['test_y']
    pred_y = result['pred_y']

    tmp = np.zeros(pred_y.shape)
    
    resmcc = []
    resf1 = []
    for t in np.arange(0,1,0.01):
        tmp[pred_y < t] = 0
        tmp[pred_y >= t] = 1
        for i in range(37):
            resmcc.append(accuracy_score(test_y[:,i], tmp[:, i]))
            resf1.append(precision_score(test_y[:,i], tmp[:, i]))
    resmcc = np.array(resmcc).reshape((100, 37))
    resf1 = np.array(resf1).reshape((100, 37))

    print('{}, acc: {:.4f}, pre: {:.4f}'.format(f, np.amax(resmcc), np.amax(resf1)))

0, acc: 0.9999, pre: 1.0000
1, acc: 0.9999, pre: 1.0000
2, acc: 0.9999, pre: 1.0000
3, acc: 0.9999, pre: 1.0000
4, acc: 0.9999, pre: 1.0000
5, acc: 0.9999, pre: 1.0000
6, acc: 0.9999, pre: 1.0000
7, acc: 0.9999, pre: 1.0000
8, acc: 0.9999, pre: 1.0000
9, acc: 0.9999, pre: 1.0000


In [125]:
resmcc = np.array(resmcc).reshape((100, 37))
resf1 = np.array(resf1).reshape((100, 37))

In [128]:
np.amax(resauc)

0.9178154314147873

In [100]:
result

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Tue Oct 13 17:07:17 2020',
 '__version__': '1.0',
 '__globals__': [],
 'pred_y': array([[7.3856791e-04, 1.6289729e-03, 3.6747148e-04, ..., 2.0673119e-03,
         7.9734059e-04, 3.6714372e-04],
        [1.2479783e-02, 4.7726668e-03, 6.7336950e-04, ..., 4.5304617e-04,
         1.5002469e-03, 3.7446222e-04],
        [2.4696470e-03, 1.6048219e-03, 5.9586775e-04, ..., 3.1644807e-04,
         9.4876916e-04, 3.6800368e-04],
        ...,
        [1.4670380e-02, 2.3559548e-03, 3.6275617e-04, ..., 3.5265419e-03,
         9.7754691e-04, 3.7543196e-04],
        [2.0957552e-04, 1.2722786e-05, 2.7459156e-04, ..., 8.2992519e-05,
         5.7043397e-04, 3.6817626e-04],
        [6.1473763e-04, 1.6422895e-03, 2.7175972e-04, ..., 1.3553054e-03,
         8.0976670e-04, 3.6877257e-04]], dtype=float32),
 'test_y': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, 

In [101]:
test_y = result['test_y']

In [102]:
pred_y = result['pred_y']

In [103]:
tmp = np.zeros(pred_y.shape)

In [71]:
tmp[pred_y < 0.3] = 0
tmp[pred_y >= 0.3] = 1

In [72]:
tmp

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [74]:
np.amin(pred_y)

0.0002426045

In [36]:
pred_y

array([[0.00218197, 0.00264921, 0.00057168, ..., 0.00567965, 0.00200361,
        0.00124048],
       [0.00150887, 0.00293693, 0.00043915, ..., 0.00382916, 0.0017069 ,
        0.00112543],
       [0.00352711, 0.00457331, 0.00062335, ..., 0.00524639, 0.00209365,
        0.00158105],
       ...,
       [0.00720586, 0.00861815, 0.00100143, ..., 0.00810077, 0.00331353,
        0.00250639],
       [0.0014179 , 0.00181723, 0.00041279, ..., 0.00410459, 0.00140878,
        0.00089761],
       [0.00190351, 0.00237175, 0.00049859, ..., 0.00317534, 0.00176481,
        0.00108573]], dtype=float32)

In [96]:
from sklearn.metrics import accuracy_score, matthews_corrcoef, f1_score, precision_score
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
accuracy_score(y_true, y_pred)

0.5

In [63]:
accuracy_score(test_y[:, 0], tmp[:, 0])

0.9960679177837355

In [117]:
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

for i in range(37):
    fpr, tpr, _ = roc_curve(test_y[:, i], pred_y[:, i])
    roc_auc = auc(fpr, tpr)
    print(roc_auc)

# # plot ROC
# import matplotlib.pyplot as plt
# plt.figure()
# plt.plot(fpr, tpr, color='darkorange',
#          lw=2, label='ROC curve (area = %0.4f)' % roc_auc)
# plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
# plt.xlim([0.0, 1.0])
# plt.ylim([0.0, 1.05])
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('Receiver operating characteristic class ')
# plt.legend(loc="lower right")
# plt.show()

0.7874716571782784
0.8889420606372046
0.8345946610624217
0.899236564540432
0.8415383501569049
0.9019988512801146
0.8763382307927763
0.8090331709617871
0.8590003758794431
0.7884208031495563
0.8675712087744055
0.8908688630490955
0.8879223612252559
0.8324986585583974
0.7203599415988796
0.9076255457364014
0.8396511627906977
0.8214246341261748
0.3845638183768323
0.8383255904177322
0.9178154314147873
0.7099970131421744
0.7865859340190187
0.576924452391596
0.873741128880909
0.8764998749009195
0.8658233691951518
0.8886244739940398
0.5304790847336431
0.880701071080818
0.8953969667570378
0.5432799785388536
0.737571530758226
0.5467993510558118
0.8021526653474846
0.868863627322274
0.7285829235583371


In [40]:
roc_auc

0.7150180252189942

In [25]:
test_y[:, 0]

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [28]:
print(pred_y[:, 0])

[0. 0. 0. ... 0. 0. 0.]


In [65]:
test_y.shape

(11190, 37)

In [116]:
for i in range(37):
    resmcc = []
    for t in np.arange(0,1,0.001):
        tmp[pred_y < t] = 0
        tmp[pred_y >= t] = 1
        resmcc.append(matthews_corrcoef(test_y[:,i], tmp[:, i]))
    print(np.amax(resmcc))

0.10598005454822297
0.20379268435989287
0.03766856326220824
0.4855190205979797
0.4878076315088179
0.31393704678906104
0.4280772035658725
0.048628721328335685
0.20002890306168425
0.17258806497009332
0.44766393769840435
0.5599142380001132
0.5158128938096403
0.04384043125749186
0.0
0.26149015779468304
0.02807669759494813
0.07253796872248466
0.0
0.2632378208705191
0.08287801564026752
0.055620820962982244
0.13704100601198935
0.0
0.5019944016582528
0.2168349330320817
0.38522493154388043
0.6304153916857096
0.0
0.29050268879527363
0.5981034111280363
0.0
0.0
0.0
0.15610795568374455
0.06527300856962985
0.0


In [115]:
np.unique(pred_y).shape

(390835,)

In [110]:
np.amax(resmcc)

0.1803921568627451

In [44]:
from sklearn.metrics import matthews_corrcoef
y_true = [+1, +1, +1, -1]
y_pred = [+1, -1, +1, +1]
matthews_corrcoef(y_true, y_pred)

-0.3333333333333333

In [49]:
tmp = np.array(tmp, dtype='uint8')

In [53]:
test_y[:, 0]

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [55]:
tmp[:,0].shape

(11190,)

In [143]:
from sklearn.metrics import label_ranking_average_precision_score as avgprec
from sklearn.metrics import coverage_error, label_ranking_loss

ap_list = []
rl_list = []
ce_list = []
for c in range(5):
    for f in range(20):
        filename = 'encoding_3106/new_encoding_3106_res_' +str(c) + '_' +  str(f) + '.mat'
        result = loadmat(filename)
        test_y = result['test_y']
        pred_y = result['pred_y']
        
        ap_list.append(avgprec(test_y, pred_y))
        rl_list.append(label_ranking_loss(test_y, pred_y))
        ce_list.append(coverage_error(test_y, pred_y) - 1)

In [144]:
ap_values = np.array(ap_list).reshape((5,20))
rl_values = np.array(rl_list).reshape((5,20))
ce_values = np.array(ce_list).reshape((5,20))
    
with open('new_encoding_3106_uni.txt', 'w') as result_file:    
    result_file.write('the ap score is: \n')
    result_file.write(str(ap_values) + '\n')
    result_file.write('max is: {}'.format(np.amax(ap_values, axis = 1)) + '\n')    
    result_file.write('k-fold is: {}'.format(np.average(ap_values, axis = 0)) + '\n')
    result_file.write('k-fold max is: {}'.format(np.amax(np.average(ap_values, axis = 0))) + '\n')

    result_file.write('the rl score is: \n')
    result_file.write(str(rl_values) + '\n')
    result_file.write('min is: {}'.format(np.amin(rl_values, axis = 1)) + '\n')    
    result_file.write('k-fold is: {}'.format(np.average(rl_values, axis = 0)) + '\n')
    result_file.write('k-fold min is: {}'.format(np.amin(np.average(rl_values, axis = 0))) + '\n')

    result_file.write('the ce score is: \n')
    result_file.write(str(ce_values) + '\n')
    result_file.write('min is: {}'.format(np.amin(ce_values, axis = 1)) + '\n')    
    result_file.write('k-fold is: {}'.format(np.average(ce_values, axis = 0)) + '\n')
    result_file.write('k-fold min is: {}'.format(np.amin(np.average(ce_values, axis = 0))) + '\n')